### ISSUE TITLE
Result-Page rendering the user's name.

### ISSUE THREAD

**Issue by otsolap** [heihazy/daily-playlist-frontend#5]
**User story:**

As a User I would like to have my username rendered in the result as the game congratulates and rewards me with the playlist of the day.

**Task:** 
Create a component that would render the user’s given username from the database. 

**Problems:**

I don’t know where to exactly start so I will be listing what I have been given thought of and what could provide solutions and answers. However, my logic is flawed and therefore I need assistance.
How to render the names by only having the specific name?

Axios.get is used to fetch username data. In our React course we used mapping and rendering to get a list of objects, which would provide a url-parameter for a specific post. In this example it could be something like localhost3000/blog which renders a list of posts and by clicking a singular post, you would get localhost3000/blog/post-one.

However, we do not want to have a page where all names are rendered unless that can be done without the user not seeing it…. However this would seem like a sloppy solution as all usernames are stored in localhost3001/usernames/ and can be found with localhost3001/usernames/:_id
how could I use either a Class Component or Functional Component to simply get that specific name? Can I do it without creating the NameCard component? Can I do it without the url parameter?

All the various examples that I’ve found in either school or stackoverflow find that the solution comes from URL parameters… Which is why I would ask now about linking.

**Linking**

From App.js:

<Route path=”/result” component={ResultPage}/>

From Result.js:

<Link to=”/result”>

I was thinking these could be replaced with ={`/result/${username._Id}`}

The logic here would be that _id reflects on the Mongoose ID that each username receives, but in order to make this work in the Result.js component I would first need to create the const usernameList = users.map((user) and include the <div key={user._id}> in there.

My problem with this solution was the lines 44-46 in Result.js because when the page-change happens the Result.propTypes get ignored and the application crashes.

Alternative could this be done via simply props from 1 page to another, but then the solution is not full-stack approached?

**Comment by bch-fullstack** [comment]
what are you using for user authentication? if it is passportjs arent you always having user info under req.user object populated by the deserialize function? @otsolap

**Comment by otsolap** [comment]
We haven't thought about user authentication because it's just a videogame and nothing with personal information attached. However if you feel strongly about having user authentication we can consider it as a group. 

The idea of the username component is just to make the game feel more personal.
